theme = "nord-dark"
icons = "awesome"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
hide_when_uptodate=true

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}"

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "battery"
format = " {percentage}"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "bluetooth"
mac = "24:5A:B5:B7:A0:42"
hide_disconnected = true
format = ""

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
on_click = "~/.i3/i3scripts/rofi-calendar/rofi-calendar"

[[block]]
block = "notify"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "| {layout} |"
interval = 1


